name: Rollout restart Logstash

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  rollout-restart-logstash:
    name: 🔃 Restart logstash indexing 
    runs-on: ubuntu-latest
    env:
      ACME: acme
      APP_GROUP: monitor
      APP_HOST: stats-api.judilibre.io
      APP_HOST_ALTER: stats-api.judilibre.io
      APP_ID: monitor
      APP_NODES: 1
      APP_SCHEME: https
      APP_PORT: 443
      API_PORT: 8080
      DOCKER_USERNAME: opendatajustice
      ELASTIC_INDEX: logstash-*
      ELASTIC_NODES: 1
      ELASTIC_MEM: 8192Mi
      ELASTIC_MEM_JVM: 4096m
      ELASTIC_SEARCH_PASSWORD: ${{ secrets.ELASTIC_SEARCH_PASSWORD }}
      ELASTIC_STORAGE_POLICY: DeleteOnScaledownOnly
      ELASTIC_STORAGE_SIZE: 50Gi
      KUBE_INGRESS: nginx
      KUBE_NAMESPACE: monitor
      KUBE_TYPE: k8s
      KUBE_ZONE: scw-monitor-par1
      SCW_LOG_BUCKET: ${{ secrets.SCW_LOG_BUCKET }}
      SCW_LOG_ARCHIVE_BUCKET: ${{ secrets.SCW_LOG_ARCHIVE_BUCKET }}
      SCW_LOG_ACCESS_KEY: ${{ secrets.SCW_LOG_ACCESS_KEY }}
      SCW_LOG_SECRET_KEY: ${{ secrets.SCW_LOG_SECRET_KEY }}
      SCW_LOG_GZIP: "true"
      SCW_KUBE_NODES: 1
      SCW_REGION: fr-par
      SCW_ZONE: fr-par-1
      START_TIMEOUT: 360
    steps:
      - uses: actions/checkout@v1
      - name: extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF} | sed 's|^refs/heads/||;' | sed 's/[^a-zA-Z0-9]/-/g')"
        id: extract_branch
      - name: init deps
        run: ./scripts/init_deps.sh
        env:
          GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
      - name: kube prerequisites
        run: |
          mkdir -p ${HOME}/.kube
          cat k8s/kubeconfig.yaml | envsubst > ~/.kube/config
        env:
          KUBE_CA: ${{ secrets.KUBE_SCW_CA }}
          KUBE_NAME: ${{ secrets.KUBE_SCW_NAME }}
          KUBE_TOKEN: ${{ secrets.KUBE_SCW_TOKEN }}
          KUBE_URL: ${{ secrets.KUBE_SCW_URL }}
          KUBE_USER: ${{ secrets.KUBE_SCW_USER }}
      - name: 🔃 Restart logstash indexing
        run: |
          kubectl --namespace=${KUBE_NAMESPACE} rollout restart deployment/logstash-deployment
